version: "3.8"

services:
  dev_postgres:
    image: postgres:latest
    container_name: dev_postgres_server # Custom container name
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devuser # Password matches the username
      POSTGRES_DB: devdatabase
    ports:
      - "10001:5432" # Maps port 10001 on the host to port 5432 on the container
