version: "3.8"

services:
  dev_postgres:
    image: postgres:latest
    container_name: dev_postgres_server
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mathonlinedb
    ports:
      - "10001:5432" # Maps port 10001 on the host to port 5432 on the container

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: dev_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Default pgAdmin login email
      PGADMIN_DEFAULT_PASSWORD: admin # Default pgAdmin password
    ports:
      - "10002:80" # Maps port 10002 on the host to port 80 on the container
    depends_on:
      - dev_postgres # Ensures pgAdmin starts after PostgreSQL
